// export { WelcomeSlide } from "./01-welcome";
export { AboutMeSlide } from "./02-about-me";
export { CourseContextSlide } from "./03-course-context";
export { ProgramSlide } from "./04-program";
export { IceBreakerSlide } from "./05-ice-breaker";
export { WhyDevxSlide } from "./06-why-devx";
export { ClassRulesSlide } from "./07-class-rules";
export { CourseScheduleSlide } from "./08-course-schedule";
export { AccessSetupSlide } from "./09-access-setup";
export { BreakSlide } from "./10-break";
export { CodingChallengesSlide } from "./11-coding-challenges";
export { SoftwareEngineerAdvantagesSlide } from "./12-software-engineer-advantages";
export { ConsistencySlide } from "./13-consistency";
export { WebHookSlide } from "./11-web-hook";
export { RequestJourneySlide } from "./12-request-journey";
export { FrontendSlide } from "./13-frontend";
export { AiActivitySlide } from "./14-ai-activity";
export { ExitTicketSlide } from "./15-exit-ticket";
